version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 